name: josh-at-artemis
version: 0.3
executables:
  site:
    main: Main.hs
    ghc-options: [-threaded, -with-rtsopts=-N]
    source-dirs:
      - src
    other-modules:
      - Site
      - Site.Compiler
      - Site.Config
      - Site.Context
      - Site.Identifier
      - Site.Layout
      - Site.Pattern
      - Site.Pattern.Directory
      - Site.Pattern.Extension
      - Site.Routes
      - Site.Rules
      - Site.Template
      - Data.Map.Set
      - Hakyll.Core
      - Hakyll.Core.Compiler.Empty
      - Hakyll.Core.Compiler.Overridable
      - Hakyll.Core.Identifier.Pattern.Singleton
      - Hakyll.Core.Item.Empty
      - Hakyll.Core.Item.Sort
      - Hakyll.Core.Metadata.Maybe
      - Hakyll.Core.Routes.Parent
      - Hakyll.Core.Rules.Singleton
      - Hakyll.Core.Config
      - Hakyll.Web
      - Hakyll.Web.Breadcrumb
      - Hakyll.Web.Extensionless
      - Hakyll.Web.FileType
      - Hakyll.Web.Glyphs
      - Hakyll.Web.Header
      - Hakyll.Web.Icon
      - Hakyll.Web.Layout
      - Hakyll.Web.Menu
      - Hakyll.Web.Pandoc.Style
      - Hakyll.Web.Sass.HotReload
      - Hakyll.Web.Slug
      - Hakyll.Web.Viewer
      - Hakyll.Web.Wallpaper

dependencies:
  - base
  - binary
  - containers
  - hakyll
  - hakyll-sass
  - hakyll-images
  - pandoc
  - aeson
  - bytestring
  - filepath
  - blaze-html
  - blaze-markup
  - text
  - text-conversions
  - monad-loops
  - MissingH
  - transformers
  - mtl
  - wai-app-static
  - mime-types
  - directory
  - tagsoup
  - process
