version: 0.1
executables:
  site:
    main: Main.hs
    ghc-options: [-threaded, -with-rtsopts=-N]
    source-dirs:
      - src
    other-modules:
      - Data.FileTree
      - Hakyll.Compiler.Overridable
      - Hakyll.Glyphs
      - Hakyll.Layout
      - Hakyll.Sass
      - Hakyll.Wallpaper

dependencies:
  - base
  - containers
  - hakyll
  - hakyll-sass
  - hakyll-images
  - pandoc
  - aeson
  - bytestring
  - filepath
  - blaze-html
  - blaze-markup
  - text
  - text-conversions
  - monad-loops
  - MissingH
  - transformers
  - mtl
  - wai-app-static
  - mime-types
  - directory
